In [2]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
# to get a specific element [row,column]
a[1,5]

13

In [4]:
a[0,5]

6

In [5]:
# To get a specific row, 0th row, : means include all columns
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
# To get a specific row,  : means include all rows, 2th column
a[:, 2]

array([ 3, 10])

In [7]:
# [start index: stop index: step size]
# 0,1 is start index, start at 0th row, 1st column
# stop at 6
# step size is 2, go from 2 to 4 to 6
a[0, 1:6:2]

array([2, 4, 6])

In [8]:
#7 is 0th element, 6 is -1st element, 5 is -2nd element
# backward counting
a[0, 1:-2:1]

array([2, 3, 4, 5])

In [9]:
# replace specific elements in the array
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [10]:
# replace all rows, 2nd column with 5
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [11]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [12]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# 0 means accessing the first array
# 1st row
# 1st column
#(which array, row, column)
b[0,1,1]

4

In [16]:
b[0,0]

array([1, 2])

In [17]:
b[0,0,:]

array([1, 2])

In [18]:
b[0,0,0]

1