In [1]:
import numpy as np
# make a simple array
a=np.array([1,2,3])
print (a)

[1 2 3]


In [2]:
# get dimension of the array
a.ndim

1

In [3]:
# make a 2D array
b=np.array([[1,2],[3,4]])
print (b)

[[1 2]
 [3 4]]


In [4]:
# get the shapes (number of rows and number of columns#)
b.shape

(2, 2)

In [5]:
# get the data type
a.dtype

dtype('int64')

In [8]:
# if you know a small number can you dtype=int32
#int16 uses 2 bytes of memory, int32 uses 4 bytes of memory, int64 uses 8
c=np.array([1,2,3], dtype='int16')
print (c)

[1 2 3]


In [9]:
# array a has int 64,int 64 stores up 8 bytes per item
a.itemsize

8

In [10]:
# the total size of the array a
a.nbytes

24

In [11]:
# array c has int 16,int 16 stores up 2 bytes per item
c.itemsize

2

In [12]:
# the total size of the array a
c.nbytes

6

In [13]:
# no. of elements in array
a.size

3

In [14]:
c.size

3

In [15]:
# total size of array=size of array * space taken up per item
a.size * a.itemsize

24

In [16]:
# Get total size of array c
c.size * c.itemsize

6

In [17]:
d=np.array([1,2,3], dtype='int32')
d.itemsize

4