In [1]:
import numpy as np

In [2]:
# s is a scalar, with 0 dimensions, hence no shape
s = 5
# to get output of s displayed
s

5

In [3]:
# v is a vector, with 1 dimensions
v = np.array([5,-2,4])
# to get output of v displayed
v

array([ 5, -2,  4])

In [4]:
# m is a matrix, with 2 dimensions
m = np.array([[5,-2,4],[-3,0,14]])
# to get output of m displayed
m

array([[ 5, -2,  4],
       [-3,  0, 14]])

In [5]:
# data type of the scalar s
type(s)

int

In [6]:
# data type of the vector v
type(v)

numpy.ndarray

In [7]:
# data type of the matrix m
type(m)

numpy.ndarray

In [8]:
# to get the scalar value also consistent with vector and matrix data types, we define a scalar as an array yo
s_array = np.array(5)
s_array

array(5)

In [9]:
# original vector
v.reshape(1,3)
v

array([ 5, -2,  4])

In [10]:
# reshape gives an array a new shape, without changing its data
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [11]:

m.shape

(2, 3)

In [12]:
v.shape

(3,)

In [14]:
# s has 0 dimensions hence s.shape gives an error as int object has no attributes
# s doesnt have any dimensions
s_array.shape

()